using Tequio.Domain.Dtos;
using Tequio.Domain.Models;

namespace Tequio.Domain.Repositories
{
    /// <summary>
    /// Contract for database operations related to authentication.
    /// </summary>
    public interface IAuthRepository
    {
        /// <summary>
        /// Creates a user and returns the identifier generated by the database.
        /// </summary>
        /// <param name="request">Registration data.</param>
        /// <param name="passwordHash">Secure password hash.</param>
        /// <param name="cancellationToken">Token used to cancel the operation.</param>
        /// <returns>The new user's identifier.</returns>
        Task<int> CreateUserAsync(
            RegisterRequestDto request,
            string passwordHash,
            CancellationToken cancellationToken = default);

        /// <summary>
        /// Gets the data required to authenticate a user.
        /// </summary>
        /// <param name="email">User email address.</param>
        /// <param name="cancellationToken">Token used to cancel the operation.</param>
        /// <returns>The authentication data, or null values when the user does not exist.</returns>
        Task<(string? UserId, string? RoleId, string? PasswordHash)> GetUserAuthDataAsync(
            string email,
            CancellationToken cancellationToken = default);

        /// <summary>
        /// Gets the data required for verification-code workflows.
        /// </summary>
        /// <param name="email">User email address.</param>
        /// <param name="cancellationToken">Token used to cancel the operation.</param>
        /// <returns>User verification data, or <see langword="null"/> when the user does not exist.</returns>
        Task<UserVerificationData?> GetUserVerificationDataAsync(
            string email,
            CancellationToken cancellationToken = default);
    }
}
