namespace Tequio.Domain.Email;

/// <summary>
/// Contains the data required to deliver an existing security code by email.
/// </summary>
public sealed class SecurityCodeEmailRequest
{
    /// <summary>
    /// Gets or sets the recipient email address.
    /// </summary>
    public required string RecipientEmail { get; init; }

    /// <summary>
    /// Gets or sets the optional recipient name used in the greeting.
    /// </summary>
    public string? RecipientName { get; init; }

    /// <summary>
    /// Gets or sets the six-digit security code generated by the authentication flow.
    /// </summary>
    public required string VerificationCode { get; init; }

    /// <summary>
    /// Gets or sets the purpose of the security code.
    /// </summary>
    public SecurityCodeEmailType Type { get; init; }

    /// <summary>
    /// Gets or sets the requested language code. Unsupported values fall back to Spanish.
    /// </summary>
    public string LanguageCode { get; init; } = "es";

    /// <summary>
    /// Gets or sets the validity period communicated to the recipient.
    /// </summary>
    public int ExpirationMinutes { get; init; } = 15;
}
